//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 3DCode.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_3DCodeTYPE                  130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_QR_ENCODE               149
#define ID_VIEW_QR_DECODE               150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_QRENCODE_DIALOG             310
#define IDD_QRDECODE_DIALOG             311
#define IDI_ICON_FLIP_H                 312
#define IDI_ICON_FLIP_V                 313
#define IDI_ICON_TRANSPOSE              314
#define IDI_ICON_ZOOM_DEFAULT           315
#define IDI_ICON_ZOOM_IN                316
#define IDI_ICON_ZOOM_OUT               317
#define IDD_MESSAGE_DIALOG              318
#define IDC_COMBOLEVEL                  1000
#define IDC_COMBOVERSION                1001
#define IDC_COMBOMASKINGNO              1002
#define IDC_CHECKAUTOEXTENT             1003
#define IDC_STATICVERSION               1004
#define IDC_STATICMASKINGNO             1005
#define IDC_EDITMODULESIZE              1006
#define IDC_SPINMODULESIZE              1007
#define IDC_STATICBMPSIZE               1008
#define IDC_EDITSOURCEDATA_PUBLIC       1009
#define IDC_EDITSOURCEDATA_PRIVATE      1010
#define IDC_IMPORT_LOGO                 1011
#define IDC_FOREGROUND_R                1012
#define IDC_FOREGROUND_G                1013
#define IDC_FOREGROUND_B                1014
#define IDC_BACKGROUND_R                1015
#define IDC_BACKGROUND_G                1016
#define IDC_BACKGROUND_B                1017
#define IDC_QRCOLOR1_R                  1018
#define IDC_QRCOLOR1_G                  1019
#define IDC_QRCOLOR1_B                  1020
#define IDC_QRCOLOR2_R                  1021
#define IDC_QRCOLOR2_G                  1022
#define IDC_QRCOLOR2_B                  1023
#define IDC_BN_FOREGROUND               1024
#define IDC_BN_BACKGROUND               1025
#define IDC_BN_ENCODE_COLOR1            1026
#define IDC_BN_ENCODE_COLOR2            1027
#define IDC_COLORS_ENCODEABLE_INFO      1028
#define IDC_COMBOLEVEL2                 1028
#define IDC_SLIDER_LOGO_WIDTH           1029
#define IDC_CHECK_USE_HYBRID            1029
#define IDC_SLIDER_LOGO_HEIGHT          1030
#define IDC_CHECK_TRY_HARDER            1031
#define IDC_COMBOMASKINGNO2             1031
#define IDC_RESET_LOGO_SIZE             1032
#define IDC_CHECK_SEARCH_MULTI          1033
#define IDC_CLEAR_LOGO                  1034
#define IDC_BUTTON_DECODE               1035
#define IDC_EDIT_EC_LEVEL               1036
#define IDC_EDIT_QR_VERSION             1037
#define IDC_EDIT_MASK_VERSION           1038
#define IDC_EDIT_MODULESIZE             1039
#define IDC_EDIT_INPUT                  1040
#define IDC_EDIT_INNER_ECLEVEL          1040
#define IDC_INPUT_NAME                  1041
#define IDC_CHECK_COLORS_QRENCODED      1041
#define IDC_EDIT_ISQRENCODED            1041
#define IDC_EDIT_INNER_MASK             1041
#define IDC_BUTTON_ENCODE               1042
#define IDC_BUTTON_SAVE_IMAGE           1043
#define IDC_SLIDER_ECLEVEL              1049
#define IDC_STATICQRCODESIZE            1050
#define IDC_BUTTON_SAVE                 1051
#define IDC_CHECK_QRDECODE              1052
#define IDC_BUTTON_CLEAR                1056
#define IDC_CHECK_COMPRESS              1058
#define ID_ENCODE_VIEW                  9999
#define ID_TOOLBAR_ENCODE               32771
#define IDC_ENABLE_MIXED                32772
#define ID_VIEW_ZOOM_IN                 32774
#define ID_VIEW_ZOOM_OUT                32776
#define ID_VIEW_ZOOM_DEFAULT            32777
#define ID_VIEW_FLIP_V                  32778
#define ID_VIEW_FLIP_H                  32779
#define ID_VIEW_TRANSPOSE               32780
#define ID_EDIT_BPP                     32784
#define ID_EDIT_ROTATE                  32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        319
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
